### PR TITLE
frontend: Fixes the text for dark mode

### PR DESCRIPTION
**Pull request by vyncent-t**
fixes https://github.com/headlamp-k8s/headlamp/issues/1878

## Description

This PR addresses the issue where text related to the "Install Prometheus Metrics Charts" parts were not visible when using dark mode. By adjusting the text color settings for dark mode, this fix ensures that all text is clearly visible, improving usability and accessibility.

## Changes

- [x] Updated CSS styles for dark mode to enhance the visibility of the text for the "Install Prometheus Metrics Charts" feature.
- [x] Tested the text visibility across different screen sizes and resolutions to ensure consistency.

## Verification

- [x] Verified that the updated text color appears correctly in dark mode and does not affect other elements' appearance.

## Screenshots

**Before**
image

**After**
image

### CODE REVIEW

**Comment by illume** [comment]
@vyncent-t `npm run build` is failing.

**Comment by vyncent-t** [comment]
@illume I think the build error is the same as this one https://github.com/headlamp-k8s/plugins/actions/runs/8440047083/job/23597895411?pr=33

**Comment by illume** [comment]
Ah right. I’ll look into it.

**Review by illume — APPROVED** [review]
🎉 thanks

**Pull request merged**
