### PR TITLE
prometheus: Update to headlamp-plugin@0.8.0-alpha.13 and mui 5

### PR DESCRIPTION
**Pull request by illume**
Updates prometheus so it works with the Headlamp main branch.

Note: You have to use this headlamp branch until it is merged in: `mui-fixes` https://github.com/headlamp-k8s/headlamp/pull/1595

## How to test

- [ ] Please test the prometheus plugin manually with latest headlamp main branch

### CODE REVIEW

**Comment by yolossn** [comment]
Tested it locally and ran into this error message.
>Plugin execution error in plugins/prometheus: TypeError: Cannot read properties of undefined (reading 'Alert')
    at @mui/material/Alert (eval at <anonymous> (index.ts:283:1), <anonymous>:139:39)
    at __webpack_require__ (eval at <anonymous> (index.ts:283:1), <anonymous>:223:41)
    at eval (common.tsx:15:77)
    at ./src/common.tsx (eval at <anonymous> (index.ts:283:1), <anonymous>:39:1)
    at __webpack_require__ (eval at <anonymous> (index.ts:283:1), <anonymous>:223:41)
    at eval (index.tsx:4:65)
    at ./src/index.tsx (eval at <anonymous> (index.ts:283:1), <anonymous>:49:1)
    at __webpack_require__ (eval at <anonymous> (index.ts:283:1), <anonymous>:223:41)
    at eval (eval at <anonymous> (index.ts:283:1), <anonymous>:275:37)
    at eval (eval at <anonymous> (index.ts:283:1), <anonymous>:277:12)
(anonymous) @ index.ts:287
(anonymous) @ index.ts:289
fetchAndExecutePlugins @ index.ts:279
await in fetchAndExecutePlugins (async)
(anonymous) @ Plugins.tsx:27
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157

image

**Comment by illume** [comment]
@yolossn Sorry. You have to use this headlamp branch until it is merged in: `mui-fixes` https://github.com/headlamp-k8s/headlamp/pull/1595

**Review by yolossn — APPROVED** [review]
Tested it locally, works as expected.

**Comment by illume** [comment]
Thanks @yolossn

**Pull request merged**
